#!/usr/bin/env python3
"""
Generate Substack draft and Twitter thread from a debate run JSON.
"""
import json
import os


def format_substack(run: dict, context: dict) -> str:
    """Generate a Substack-ready markdown post from a debate run."""
    decision = run["decision"]
    home = context.get("home_team", "Home")
    away = context.get("away_team", "Away")
    home_g = decision["home_goals"]
    away_g = decision["away_goals"]
    confidence_pct = int(decision.get("confidence", 0) * 100)
    upset_pct = int(decision.get("upset_probability", 0) * 100)
    quote = decision.get("studio_banter_quote") or {"role": "Council", "exchange": "The debate produced a unanimous prediction."}
    key_factors = decision.get("key_factors", [])
    dissenting = decision.get("dissenting_views", [])

    # Form strings
    def form_str(form_list):
        if not form_list:
            return "N/A"
        return " ".join(form_list)

    injuries_home = context.get("injuries_home") or []
    injuries_away = context.get("injuries_away") or []
    odds = context.get("odds") or {}

    debate = run.get("full_debate", {})
    proposals = debate.get("proposals", {})
    critiques = debate.get("cross_critiques", {})
    rebuttals = debate.get("rebuttals", {})

    lines = [
        f"# ⚽ {home} vs {away} — The Council's Verdict",
        "",
        f"*AI Football Night — four AI pundits with very different opinions, debating so you don't have to.*",
        "",
        "---",
        "",
        "## The Sharpest Exchange",
        "",
        f"> {quote.get('exchange', quote.get('quote', ''))}",
        "",
        "---",
        "",
        "## The Prediction",
        "",
        f"**{home} {home_g}–{away_g} {away}**",
        "",
        f"Confidence: {confidence_pct}% | Upset probability: {upset_pct}%",
        "",
        "---",
        "",
        "## What the Council Saw",
        "",
    ]
    for factor in key_factors:
        lines.append(f"- {factor}")
    lines.append("")

    if dissenting:
        lines += ["**Dissenting views:**", ""]
        for view in dissenting:
            lines.append(f"- *{view}*")
        lines.append("")

    lines += ["---", "", "## Match Context", ""]

    if context.get("group"):
        lines.append(f"**Group {context['group']}** | {context.get('match_date', 'TBD')}")
        lines.append("")

    if context.get("h2h_summary"):
        lines += [f"**H2H:** {context['h2h_summary']}", ""]

    lines.append(f"**Recent form:** {home} {form_str(context.get('form_home'))} | {away} {form_str(context.get('form_away'))}")
    lines.append("")

    if injuries_home or injuries_away:
        lines.append("**Injuries:**")
        for inj in injuries_home:
            lines.append(f"- {home}: {inj}")
        for inj in injuries_away:
            lines.append(f"- {away}: {inj}")
        lines.append("")

    if odds.get("home_win"):
        lines.append(f"**Odds:** {home} {odds['home_win']} | Draw {odds.get('draw', '?')} | {away} {odds.get('away_win', '?')}")
        lines.append("")

    lines += ["---", "", "## The Full Debate", ""]

    if proposals:
        lines.append("### Round 1 — Initial Positions")
        lines.append("")
        for role, text in proposals.items():
            lines.append(f"**{role}:** {text[:400]}{'...' if len(text) > 400 else ''}")
            lines.append("")

    if critiques:
        lines.append("### Round 2 — Cross-Critiques")
        lines.append("")
        for role, text in critiques.items():
            lines.append(f"**{role}:** {text[:300]}{'...' if len(text) > 300 else ''}")
            lines.append("")

    if rebuttals:
        lines.append("### Round 3 — Rebuttals")
        lines.append("")
        for role, text in rebuttals.items():
            lines.append(f"**{role}:** {text[:300]}{'...' if len(text) > 300 else ''}")
            lines.append("")

    lines += [
        "### The Verdict",
        "",
        decision.get("rationale", ""),
        "",
        "---",
        "",
        "*Generated by [AI Football Night](https://github.com/krishnancr/ai-football-night) — open source multi-model debate engine.*",
        f"*Subscribe for daily World Cup predictions: {os.getenv('SUBSTACK_URL', 'link in bio')}*",
        "",
    ]

    return "\n".join(lines)


def format_twitter_thread(run: dict, context: dict) -> list:
    """Generate a Twitter thread as a list of tweet strings (each ≤280 chars)."""
    decision = run["decision"]
    home = context.get("home_team", "Home")
    away = context.get("away_team", "Away")
    home_g = decision["home_goals"]
    away_g = decision["away_goals"]
    confidence_pct = int(decision.get("confidence", 0) * 100)
    banter = decision.get("studio_banter_quote") or {"role": "Council", "exchange": "The panel reached a unanimous verdict."}
    match_headline = decision.get("match_headline", f"{home} vs {away} — The Council's Verdict")
    key_factors = decision.get("key_factors", [])
    outrageous = decision.get("most_outrageous_take") or (key_factors[1] if len(key_factors) > 1 else key_factors[0] if key_factors else "")
    host_intro = decision.get("host_intro") or decision.get("rationale", "")[:120]
    substack_url = os.getenv("SUBSTACK_URL", "link in bio")

    proposals = run.get("full_debate", {}).get("proposals", {})
    statman_text = proposals.get("Stat_Bot") or proposals.get("Statman", "")

    def truncate(text: str, max_len: int) -> str:
        if len(text) <= max_len:
            return text
        return text[:max_len - 1] + "…"

    exchange_text = truncate(banter.get("exchange", ""), 210)

    hook = decision.get("tweet_hook", "")
    hook_line = f"\n\n{hook}" if hook else ""

    stat_highlight = decision.get("stat_bot_highlight", "")
    if not stat_highlight:
        # fallback: first 200 chars of Stat_Bot proposal
        stat_highlight = statman_text[:200] + ("…" if len(statman_text) > 200 else "")

    return [
        truncate(f"🏟️ {match_headline}\n\n{home} {home_g}–{away_g} {away} — {confidence_pct}% panel confidence{hook_line}\n\nThe panel got heated 👇 [1/5]", 280),
        truncate(f"💬 {banter['role']}:\n\n{exchange_text}\n\n[2/5]", 280),
        truncate(f"📊 Stat_Bot:\n\n{stat_highlight}\n\n[3/5]", 280),
        truncate(f"🔥 Most outrageous take:\n\n{outrageous}\n\n[4/5]", 280),
        truncate(f"⚖️ Host's call:\n\n{host_intro}\n\nFull debate → {substack_url}\n\n[5/5]", 280),
    ]
