#!/usr/bin/env python3
"""
Generate Substack draft and Twitter thread from a debate run JSON.
"""
import json
import os


def format_substack(run: dict, context: dict) -> str:
    """Generate a Substack-ready markdown post from a debate run."""
    decision = run["decision"]
    home = context.get("home_team", "Home")
    away = context.get("away_team", "Away")
    home_g = decision["home_goals"]
    away_g = decision["away_goals"]
    confidence_pct = int(decision.get("confidence", 0) * 100)
    upset_pct = int(decision.get("upset_probability", 0) * 100)
    quote = decision.get("studio_banter_quote") or {"role": "Council", "exchange": "The debate produced a unanimous prediction."}
    key_factors = decision.get("key_factors", [])
    dissenting = decision.get("dissenting_views", [])

    # Form strings
    def form_str(form_list):
        if not form_list:
            return "N/A"
        return " ".join(form_list)

    injuries_home = context.get("injuries_home") or []
    injuries_away = context.get("injuries_away") or []
    odds = context.get("odds") or {}

    debate = run.get("full_debate", {})
    proposals = debate.get("proposals", {})
    critiques = debate.get("cross_critiques", {})
    rebuttals = debate.get("rebuttals", {})

    lines = [
        f"# ⚽ {home} vs {away} — The Council's Verdict",
        "",
        f"*AI Football Night — four AI pundits with very different opinions, debating so you don't have to.*",
        "",
        "---",
        "",
        "## The Sharpest Exchange",
        "",
        f"> {quote.get('exchange', quote.get('quote', ''))}",
        "",
        "---",
        "",
        "## The Prediction",
        "",
        f"**{home} {home_g}–{away_g} {away}**",
        "",
        f"Confidence: {confidence_pct}% | Upset probability: {upset_pct}%",
        "",
        "---",
        "",
        "## What the Council Saw",
        "",
    ]
    for factor in key_factors:
        lines.append(f"- {factor}")
    lines.append("")

    if dissenting:
        lines += ["**Dissenting views:**", ""]
        for view in dissenting:
            lines.append(f"- *{view}*")
        lines.append("")

    lines += ["---", "", "## Match Context", ""]

    if context.get("group"):
        lines.append(f"**Group {context['group']}** | {context.get('match_date', 'TBD')}")
        lines.append("")

    if context.get("h2h_summary"):
        lines += [f"**H2H:** {context['h2h_summary']}", ""]

    lines.append(f"**Recent form:** {home} {form_str(context.get('form_home'))} | {away} {form_str(context.get('form_away'))}")
    lines.append("")

    if injuries_home or injuries_away:
        lines.append("**Injuries:**")
        for inj in injuries_home:
            lines.append(f"- {home}: {inj}")
        for inj in injuries_away:
            lines.append(f"- {away}: {inj}")
        lines.append("")

    if odds.get("home_win"):
        lines.append(f"**Odds:** {home} {odds['home_win']} | Draw {odds.get('draw', '?')} | {away} {odds.get('away_win', '?')}")
        lines.append("")

    lines += ["---", "", "## The Full Debate", ""]

    if proposals:
        lines.append("### Round 1 — Initial Positions")
        lines.append("")
        for role, text in proposals.items():
            lines.append(f"**{role}:** {text[:400]}{'...' if len(text) > 400 else ''}")
            lines.append("")

    if critiques:
        lines.append("### Round 2 — Cross-Critiques")
        lines.append("")
        for role, text in critiques.items():
            lines.append(f"**{role}:** {text[:300]}{'...' if len(text) > 300 else ''}")
            lines.append("")

    if rebuttals:
        lines.append("### Round 3 — Rebuttals")
        lines.append("")
        for role, text in rebuttals.items():
            lines.append(f"**{role}:** {text[:300]}{'...' if len(text) > 300 else ''}")
            lines.append("")

    lines += [
        "### The Verdict",
        "",
        decision.get("rationale", ""),
        "",
        "---",
        "",
        "*Generated by [AI Football Night](https://github.com/krishnancr/ai-football-night) — open source multi-model debate engine.*",
        f"*Subscribe for daily World Cup predictions: {os.getenv('SUBSTACK_URL', 'link in bio')}*",
        "",
    ]

    return "\n".join(lines)


# Legacy role keys (older runs) -> current display names.
_LEGACY_ROLES = {"Statman": "Stat_Bot", "TacticalAnalyst": "G_Bot", "Contrarian": "R_Bot", "Judge": "K_Bot"}


def _lean(home_goals: int, away_goals: int) -> str:
    return "H" if home_goals > away_goals else ("A" if away_goals > home_goals else "D")


def format_twitter_thread(run: dict, context: dict) -> list:
    """Twitter thread (each ≤280 chars) matching the picks card: the 4-way pick
    divergence, the lone outlier, and the judge's verdict — not the old banter snippet."""
    from collections import Counter
    from track_record import extract_pundit_predictions

    decision = run["decision"]
    home = context.get("home_team") or run.get("match_string", "Home vs Away").split(" vs ")[0].strip()
    away = context.get("away_team") or (run.get("match_string", " vs ").split(" vs ")[-1].strip() or "Away")
    home_g = decision["home_goals"]
    away_g = decision["away_goals"]
    confidence_pct = int(decision.get("confidence", 0) * 100)
    match_headline = decision.get("match_headline", f"{home} vs {away} — the panel's verdict")
    key_factors = decision.get("key_factors", [])
    outrageous = decision.get("most_outrageous_take") or (key_factors[0] if key_factors else "")
    host_intro = decision.get("host_intro") or decision.get("rationale", "")[:120]
    substack_url = os.getenv("SUBSTACK_URL", "link in bio")
    hook = decision.get("tweet_hook", "")
    hook_line = f"\n\n{hook}" if hook else ""

    # Predictions: prefer structured field, else parse "PREDICTION:" lines; normalize legacy keys.
    preds_raw = run.get("pundit_predictions") or extract_pundit_predictions(run.get("full_debate", {}))
    preds = {_LEGACY_ROLES.get(k, k): v for k, v in preds_raw.items()}

    def truncate(text: str, max_len: int = 280) -> str:
        return text if len(text) <= max_len else text[:max_len - 1] + "…"

    # 1/4 — hook + verdict (the card's headline). Trim the HOOK to fit, never the
    # verdict/CTA/marker — those must always survive.
    head_verdict = (f"🏟️ {match_headline}\n\n{home} {home_g}–{away_g} {away} "
                    f"— the panel's verdict ({confidence_pct}% confidence)")
    closing = "\n\nBut our 4 AI pundits didn't all agree 👇 [1/4]"
    room = 280 - len(head_verdict) - len(closing) - 2  # 2 = "\n\n" before hook
    if hook and room > 12:
        hook_fit = hook if len(hook) <= room else hook[:room - 1] + "…"
        tweet1 = f"{head_verdict}\n\n{hook_fit}{closing}"
    else:
        tweet1 = head_verdict + closing
    tweet1 = truncate(tweet1)

    # 2/4 — the divergence shown on the card
    order = ["Stat_Bot", "G_Bot", "R_Bot"]
    pick_lines = [f"{r} {preds[r]['home_goals']}-{preds[r]['away_goals']}" for r in order if r in preds]
    leans = {r: _lean(preds[r]["home_goals"], preds[r]["away_goals"]) for r in order if r in preds}
    counts = Counter(leans.values())
    minority = [r for r, lv in leans.items() if counts[lv] == 1] if len(counts) > 1 else []
    outlier_line = f"\n\n{minority[0]} is the outlier." if len(minority) == 1 else ""
    if pick_lines:
        tweet2 = truncate("The panel's calls:\n\n" + "\n".join(pick_lines)
                          + f"\n\n⚖️ Verdict: {home_g}-{away_g}{outlier_line} [2/4]")
    else:
        tweet2 = truncate(f"⚖️ The panel's verdict: {home} {home_g}–{away_g} {away}.\n\n"
                          "Four bots, one final call. [2/4]")

    # 3/4 — debate bait
    tweet3 = truncate(f"🔥 The most outrageous take:\n\n{outrageous} [3/4]")

    # 4/4 — host's call + where to read the full debate
    tweet4 = truncate(f"⚖️ {host_intro}\n\nFull debate → {substack_url} [4/4]")

    return [tweet1, tweet2, tweet3, tweet4]
